Testing `suite-with-failures'.
This run has ID `<uuid>'.

  ...           test-a          0   Passing.  [OK]          test-a          0   Passing.
  ...           test-a          1   Failing.> [FAIL]        test-a          1   Failing.
  ...           test-b          0   Another pass.  [OK]          test-b          0   Another pass.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        test-a          1   Failing.                                   │
└──────────────────────────────────────────────────────────────────────────────┘
[invalid] Failing test

Logs saved to `<build-context>/_build/_tests/<test-dir>/test-a.001.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `<build-context>/_build/_tests/<test-dir>'.
1 failure! in <test-duration>s. 3 tests run.
